apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: redhat-provider-secret
type: Opaque
stringData:
  ocmRefreshToken: eyJ...
---
apiVersion: redhat.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: redhat
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: redhat-provider-secret
      key: ocmRefreshToken
  endpoint: https://api.openshift.com
