apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-redhat
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/stehessel/provider-redhat
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The Red Hat Crossplane provider adds support for managing Red Hat cloud
      resources in Kubernetes.

spec:
  controller:
    image: DOCKER_REGISTRY/provider-redhat-controller:VERSION
